export const monthYear = [
  { name: "January", id: 0 },
  { name: "February", id: 1 },
  { name: "March", id: 2 },
  { name: "April", id: 3 },
  { name: "May", id: 4 },
  { name: "June", id: 5 },
  { name: "July", id: 6 },
  { name: "August", id: 7 },
  { name: "September", id: 8 },
  { name: "October", id: 9 },
  { name: "November", id: 10 },
  { name: "December", id: 11 },
];

export const studentStatus = [
  {
    id: "border",
    name: "Border",
  },
  {
    id: "freshBorder",
    name: "Fresh Border",
  },
  {
    id: "freshDay",
    name: "Fresh Day",
  },
  {
    id: "day",
    name: "Day",
  },
];

export const schoolDepart = [
  { name: "arts", id: "Arts and History" },
  { name: "science", id: "Science and technolodge" },
  { name: "languages", id: "Languages" },
  { name: "commercials", id: "Commercials" },
  { name: "sports", id: "Sports " },
];

export const incomeCat = ["donations", "prices", "projects", "others"];

export const expenditureCat = [
  "Advertising and Marketing",
  "Automobile Expense",
  "Consultant Expense",
  "Credit Card Charges",
  "Depreciation Expense",
  "IT and Internet Expenses",
  "Janitorial Expense",
  "Lodging",
  "Meals and Entertainment",
  "Office Supplies",
  "Postage",
  "Printing and Stationery",
  "Rent Expense ",
  "Repairs and Maintenance",
  "Salaries and Expenses Wages",
  "Telephone Expense",
  "Travel Expense",
  "Fixed Assets",
  "Expenses",
  "SNNIT",
  "Bank Charges",
  "Cleaning and Sanitation",
  "Fuel/Lubrication",
  "Vehicle Maintenance",
  "Accountancy",
  "Learning Materials",
  "Proprietor Drawings",
  "Donation/Gift",
  "Permit/Levies/Rates",
  "Electricity",
  "Water",
  "Text Book",
  "Note books",
  "School Uniform",
  "Exams Printing",
  "Maintenance",
  "Others",
];

export const bankOptions = [
  "Access Bank Ghana",
  "African Investment Bank",
  "Agricultural Developement Bank of Ghana",
  "Ahantaman Rural Bank",
  "CAL Bank",
  "Ecobank Ghana",
  "Fidelity Bank",
  "Intercontinental Bank",
  "HFC Bank",
  "Consolidated Bank of Ghana",
  "Barclays Bank",
  "Merchant Bank Ghana Limited",
  "Guaranty Trust Bank",
  "Stanbic",
  "Standard Chartered Bank",
  "National City Bank",
  "Northern City Bank",
  "Trust Bank",
  "UT Bank",
  "United Bank for Africa",
  "Zenith Bank",
];

export const staffPosition = [
  "Teacher",
  "Headmaster",
  "Accountant",
  "Teller",
  "Security",
  "Proprietor",
  "Cleaner",
  "Cook",
  "Admin",
  "Technician",
  "Janitor",
  "Matron",
  "Secretary",
  "Driver",
];
